function gwtcanvasdemo(){var O='',vb='" for "gwt:onLoadErrorFn"',tb='" for "gwt:onPropertyErrorFn"',hb='"><\/script>',Y='#',Tb='.cache.html',$='/',Nb='031C8FFA50043F8B9D205E17178394D6',Ob='0C0727212B9A0A5E9F796188307979EA',Pb='7ECB8D101E97B9AF2E45E8602AE294DC',Qb='914EF483F803B367525DA827BB1BA887',Sb=':',nb='::',_b='<script defer="defer">gwtcanvasdemo.onInjectionDone(\'gwtcanvasdemo\')<\/script>',gb='<script id="',qb='=',Z='?',Rb='AD291E331EA403D9CC3F01B9B5C29FAA',sb='Bad handler "',$b='DOMContentLoaded',ib='SCRIPT',fb='__gwt_marker_gwtcanvasdemo',jb='base',bb='baseUrl',S='begin',R='bootstrap',ab='clear.cache.gif',pb='content',X='end',Hb='gecko',Ib='gecko1_8',T='gwt.codesvr=',U='gwt.hosted=',V='gwt.hybrid',Ub='gwt/standard/standard.css',ub='gwt:onLoadErrorFn',rb='gwt:onPropertyErrorFn',ob='gwt:property',P='gwtcanvasdemo',db='gwtcanvasdemo.nocache.js',mb='gwtcanvasdemo::',Zb='head',Lb='hosted.html?gwtcanvasdemo',Yb='href',Gb='ie6',Fb='ie8',wb='iframe',_='img',xb="javascript:''",Vb='link',Kb='loadExternalRefs',kb='meta',zb='moduleRequested',W='moduleStartup',Eb='msie',lb='name',Bb='opera',yb='position:absolute;width:0;height:0;border:none',Wb='rel',Db='safari',cb='script',Mb='selectingPermutation',Q='startup',Xb='stylesheet',eb='undefined',Jb='unknown',Ab='user.agent',Cb='webkit';var l=window,m=document,n=l.__gwtStatsEvent?function(a){return l.__gwtStatsEvent(a)}:null,o=l.__gwtStatsSessionId?l.__gwtStatsSessionId:null,p,q,r,s=O,t={},u=[],v=[],w=[],x=0,y,z;n&&n({moduleName:P,sessionId:o,subSystem:Q,evtGroup:R,millis:(new Date).getTime(),type:S});if(!l.__gwt_stylesLoaded){l.__gwt_stylesLoaded={}}if(!l.__gwt_scriptsLoaded){l.__gwt_scriptsLoaded={}}function A(){var b=false;try{var c=l.location.search;return (c.indexOf(T)!=-1||(c.indexOf(U)!=-1||l.external&&l.external.gwtOnLoad))&&c.indexOf(V)==-1}catch(a){}A=function(){return b};return b}
function B(){if(p&&q){var b=m.getElementById(P);var c=b.contentWindow;if(A()){c.__gwt_getProperty=function(a){return G(a)}}gwtcanvasdemo=null;c.gwtOnLoad(y,P,s,x);n&&n({moduleName:P,sessionId:o,subSystem:Q,evtGroup:W,millis:(new Date).getTime(),type:X})}}
function C(){function e(a){var b=a.lastIndexOf(Y);if(b==-1){b=a.length}var c=a.indexOf(Z);if(c==-1){c=a.length}var d=a.lastIndexOf($,Math.min(c,b));return d>=0?a.substring(0,d+1):O}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=m.createElement(_);b.src=a+ab;a=e(b.src)}return a}
function g(){var a=E(bb);if(a!=null){return a}return O}
function h(){var a=m.getElementsByTagName(cb);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(db)!=-1){return e(a[b].src)}}return O}
function i(){var a;if(typeof isBodyLoaded==eb||!isBodyLoaded()){var b=fb;var c;m.write(gb+b+hb);c=m.getElementById(b);a=c&&c.previousSibling;while(a&&a.tagName!=ib){a=a.previousSibling}if(c){c.parentNode.removeChild(c)}if(a&&a.src){return e(a.src)}}return O}
function j(){var a=m.getElementsByTagName(jb);if(a.length>0){return a[a.length-1].href}return O}
var k=g();if(k==O){k=h()}if(k==O){k=i()}if(k==O){k=j()}if(k==O){k=e(m.location.href)}k=f(k);s=k;return k}
function D(){var b=document.getElementsByTagName(kb);for(var c=0,d=b.length;c<d;++c){var e=b[c],f=e.getAttribute(lb),g;if(f){f=f.replace(mb,O);if(f.indexOf(nb)>=0){continue}if(f==ob){g=e.getAttribute(pb);if(g){var h,i=g.indexOf(qb);if(i>=0){f=g.substring(0,i);h=g.substring(i+1)}else{f=g;h=O}t[f]=h}}else if(f==rb){g=e.getAttribute(pb);if(g){try{z=eval(g)}catch(a){alert(sb+g+tb)}}}else if(f==ub){g=e.getAttribute(pb);if(g){try{y=eval(g)}catch(a){alert(sb+g+vb)}}}}}}
function E(a){var b=t[a];return b==null?null:b}
function F(a,b){var c=w;for(var d=0,e=a.length-1;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
function G(a){var b=v[a](),c=u[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(z){z(a,d,b)}throw null}
var H;function I(){if(!H){H=true;var a=m.createElement(wb);a.src=xb;a.id=P;a.style.cssText=yb;a.tabIndex=-1;m.body.appendChild(a);n&&n({moduleName:P,sessionId:o,subSystem:Q,evtGroup:W,millis:(new Date).getTime(),type:zb});a.contentWindow.location.replace(s+K)}}
v[Ab]=function(){var b=navigator.userAgent.toLowerCase();var c=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(b.indexOf(Bb)!=-1){return Bb}else if(b.indexOf(Cb)!=-1){return Db}else if(b.indexOf(Eb)!=-1){if(m.documentMode>=8){return Fb}else{var d=/msie ([0-9]+)\.([0-9]+)/.exec(b);if(d&&d.length==3){var e=c(d);if(e>=6000){return Gb}}}}else if(b.indexOf(Hb)!=-1){return Ib}return Jb};u[Ab]={gecko1_8:0,ie6:1,ie8:2,opera:3,safari:4};gwtcanvasdemo.onScriptLoad=function(){if(H){q=true;B()}};gwtcanvasdemo.onInjectionDone=function(){p=true;n&&n({moduleName:P,sessionId:o,subSystem:Q,evtGroup:Kb,millis:(new Date).getTime(),type:X});B()};D();C();var J;var K;if(A()){if(l.external&&(l.external.initModule&&l.external.initModule(P))){l.location.reload();return}K=Lb;J=O}n&&n({moduleName:P,sessionId:o,subSystem:Q,evtGroup:R,millis:(new Date).getTime(),type:Mb});if(!A()){try{F([Fb],Nb);F([Gb],Ob);F([Ib],Pb);F([Bb],Qb);F([Db],Rb);J=w[G(Ab)];var L=J.indexOf(Sb);if(L!=-1){x=Number(J.substring(L+1));J=J.substring(0,L)}K=J+Tb}catch(a){return}}var M;function N(){if(!r){r=true;if(!__gwt_stylesLoaded[Ub]){var a=m.createElement(Vb);__gwt_stylesLoaded[Ub]=a;a.setAttribute(Wb,Xb);a.setAttribute(Yb,s+Ub);m.getElementsByTagName(Zb)[0].appendChild(a)}B();if(m.removeEventListener){m.removeEventListener($b,N,false)}if(M){clearInterval(M)}}}
if(m.addEventListener){m.addEventListener($b,function(){I();N()},false)}var M=setInterval(function(){if(/loaded|complete/.test(m.readyState)){I();N()}},50);n&&n({moduleName:P,sessionId:o,subSystem:Q,evtGroup:R,millis:(new Date).getTime(),type:X});n&&n({moduleName:P,sessionId:o,subSystem:Q,evtGroup:Kb,millis:(new Date).getTime(),type:S});m.write(_b)}
gwtcanvasdemo();